INFO:conversation_id:1566508188450562051: [2022-09-05 21:20:09,731] Start Crawling...
WARNING:conversation_id:1566508188450562051: [2022-09-05 21:20:09,731] [WinError 183] Cannot create a file when that file already exists: 'data'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data'
INFO:conversation_id:1566508188450562051: [2022-09-05 21:20:09,988] Crawling Finished...
INFO:conversation_id:1566508188450562051: [2022-09-05 21:20:47,713] Start Crawling...
WARNING:conversation_id:1566508188450562051: [2022-09-05 21:20:47,714] [WinError 183] Cannot create a file when that file already exists: 'data'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data'
INFO:conversation_id:1566508188450562051: [2022-09-05 21:20:47,999] Crawling Finished...
INFO:conversation_id:1566508188450562051: [2022-09-05 21:21:11,506] Start Crawling...
WARNING:conversation_id:1566508188450562051: [2022-09-05 21:21:11,506] [WinError 183] Cannot create a file when that file already exists: 'data'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data'
INFO:conversation_id:1566508188450562051: [2022-09-05 21:21:11,796] Crawling Finished...
INFO:conversation_id:1566507551365144578: [2022-09-05 21:22:09,862] Start Crawling...
WARNING:conversation_id:1566507551365144578: [2022-09-05 21:22:09,863] [WinError 183] Cannot create a file when that file already exists: 'data'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data'
INFO:conversation_id:1566507551365144578: [2022-09-05 21:22:10,268] count: 14 	 Total: 14
INFO:conversation_id:1566507551365144578: [2022-09-05 21:22:15,253] Crawling Finished...
INFO:conversation_id:1566508188450562051: [2022-09-05 21:22:39,251] Start Crawling...
WARNING:conversation_id:1566508188450562051: [2022-09-05 21:22:39,252] [WinError 183] Cannot create a file when that file already exists: 'data'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data'
INFO:conversation_id:1566508188450562051: [2022-09-05 21:22:39,512] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 15:02:36,486] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 15:02:36,489] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 15:02:39,330] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 15:02:39,888] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 15:03:45,141] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 15:03:45,142] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 15:03:47,866] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 15:03:47,974] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 15:03:52,880] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:06:14,674] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:06:14,674] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:06:16,965] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:06:16,990] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:06:21,976] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:07:22,011] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:07:22,011] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:07:23,840] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 44, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:07:23,860] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:07:28,858] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:15:25,761] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:15:25,761] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:15:28,175] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:16:45,893] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:16:45,894] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:16:49,268] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:18:00,946] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:18:00,946] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:18:03,052] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:18:12,438] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:18:12,438] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:18:14,030] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:18:14,063] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:18:19,049] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:55:01,721] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:55:01,721] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:55:04,169] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:55:04,197] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 16:55:09,180] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:40:29,293] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:40:29,391] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:40:31,533] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:40:31,588] count: 190 	 Total: 190
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:40:36,542] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:49:30,096] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:49:30,096] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:49:32,267] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:49:32,291] count: 190 	 Total: 190
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:49:37,284] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:50:48,547] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:50:48,548] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:50:50,977] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:50:51,002] count: 190 	 Total: 190
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 18:50:55,986] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:14:46,635] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:14:46,635] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:14:49,342] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:14:49,376] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:15:06,910] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:15:06,910] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:15:09,102] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:15:09,130] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:15:14,116] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:17:25,688] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:17:25,688] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:17:29,714] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:17:29,739] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:17:34,720] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:20:25,789] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:20:25,791] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:20:28,385] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:20:28,409] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:20:33,397] Crawling Finished...
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:20:57,983] Start Crawling...
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:20:57,983] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen'
WARNING:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:21:01,117] [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
Traceback (most recent call last):
  File "d:\UCB - Niloufar\Crawling\TwitterApi\tweet_api.py", line 58, in create_new_directory
    mkdir(path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'data/I_apologize_harassed_isquote_-isretweet_langen/page1'
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:21:01,148] count: 191 	 Total: 191
INFO:I apologize harassed is:quote -is:retweet lang:en: [2022-09-06 20:21:06,138] Crawling Finished...
